#3 - Listar/Editar Categorias e SubCategoria
tgspn/gestao-financeira-doo pull request #40
Opened 2020-08-02 06:02 UTC by MessiasOli

2020-08-04 00:51 UTC, tgspn requested changes
@MessiasOli 
Fiz algumas observações importantes em alguns arquivos.
Qualquer dúvida, me deixe saber.

2020-08-04 00:51 UTC, tgspn commented on GestaoFinanceira/GestaoFinanceira/Model/SubCategories.cs
> +        private string Descricao { get; set; }
Neste caso as propriedades precisam ser públicas, senão não será possivel acessa-las de fora

2020-08-04 00:51 UTC, tgspn commented on GestaoFinanceira/GestaoFinanceira/Model/Categories.cs
> +
Aqui também, deixar elas publicas

2020-08-04 00:51 UTC, tgspn commented on GestaoFinanceira/GestaoFinanceira/Controller/CrtSubCategories.cs
> +            return null;
Quando prevemos um código, porém, não o implementamos, o ideal é definir ele, entretanto às vezes, é necessário já deixá-lo definido para poder desenrolar outras features. Neste caso, é uma boa prática, ao invez de retornar nulo, gerar uma exceção. 

```suggestion
           throw new NotImplementedException();
```

Desta forma, você evita que alguém chame esse método acreditando que está implementado.

2020-08-04 00:51 UTC, tgspn commented on GestaoFinanceira/GestaoFinanceira/Controller/CrtCategories.cs
> +            return null;
Foi comentado ali em baixo, sobre retornar `null`

2020-08-05 00:52 UTC, MessiasOli commented on GestaoFinanceira/GestaoFinanceira/Model/SubCategories.cs
> +        private string Descricao { get; set; }
Feito!

2020-08-05 00:53 UTC, MessiasOli commented on GestaoFinanceira/GestaoFinanceira/Model/Categories.cs
> +
Feito!

2020-08-05 01:01 UTC, MessiasOli commented on GestaoFinanceira/GestaoFinanceira/Controller/CrtSubCategories.cs
> +            return null;
Ahh que legal, não conhecia esse método de passar uma Exception em um método não implementado. Obrigado pelos apontamentos!

2020-08-05 02:17 UTC, tgspn approved these changes

2020-08-05 02:17 UTC, merged