ready to review
tgspn/gestao-financeira-doo pull request #54
Opened 2020-08-08 18:10 UTC by MessiasOli

2020-08-10 21:21 UTC, tgspn requested changes
Depois da aula de hoje, seria legal a gente discutir uns pontos deste PR

2020-08-10 21:21 UTC, tgspn commented on GestaoFinanceira/GestaoFinanceira/Model/PaymentMethod.cs
> +}
@MessiasOli depois quero ver com você se temos uma melhor implementação desta interface

2020-08-10 21:21 UTC, tgspn commented on GestaoFinanceira/GestaoFinanceira/Controllers/CategoriesController.cs
> +            this.memorySQLConnection = memorySQLConnection;
Este construtor não é necessário, pois o `MemorySQLConnection<>` implementa a interface `IConnection<>`

2020-08-16 02:06 UTC, MessiasOli commented on GestaoFinanceira/GestaoFinanceira/Model/PaymentMethod.cs
> +}
Então eu transformei ela em uma classe Pai, para dar certo algumas implementações. veja na #17

2020-08-16 20:18 UTC, tgspn approved these changes

2020-08-16 20:18 UTC, merged