feat(ListAccount)
tgspn/gestao-financeira-doo pull request #55
Opened 2020-08-08 19:09 UTC by MessiasOli

2020-08-10 21:28 UTC, tgspn requested changes
Tem alguns código que acho que vai dar conflito

2020-08-10 21:28 UTC, tgspn commented on GestaoFinanceira/GestaoFinanceira/BD/DAO/CreditCardDAO.cs
> +            return "CreditCard";
Pra banco de dados, é normal utilizar outro padrão, tudo em caixa baixa e separado com `-` exemplo:

```suggestion
            return "credit-card";

```

2020-08-10 21:28 UTC, tgspn commented on GestaoFinanceira/GestaoFinanceira/Controllers/CategoriesController.cs
> +            this.memorySQLConnection = memorySQLConnection;
Este construtor também não é necessário, pois temos o construtor com interface.

2020-08-10 21:28 UTC, tgspn commented on GestaoFinanceira/GestaoFinanceira/Model/PaymentMethod.cs
> +}
acho que isso aqui vai dar conflito com a outra branch

2020-08-16 01:55 UTC, MessiasOli commented on GestaoFinanceira/GestaoFinanceira/BD/DAO/CreditCardDAO.cs
> +            return "CreditCard";
Gostei da ideia, acho que vale a pena criar um cartão para essas edições também, ou se quiser aplicar fique a vontade.

2020-08-16 01:59 UTC, MessiasOli commented on GestaoFinanceira/GestaoFinanceira/Controllers/CategoriesController.cs
> +            this.memorySQLConnection = memorySQLConnection;
Ops! haha Corrigindo OBS: Estou aplicando essas modificações na #17

2020-08-16 02:02 UTC, MessiasOli commented on GestaoFinanceira/GestaoFinanceira/Model/PaymentMethod.cs
> +}
Eu na verdade não sei o que é isso kkk... Acredito que não estamos usando.... Esta diagrama de classes, mas já removi. OBS: Estou aplicando essas modificações na #17

2020-08-16 20:19 UTC, tgspn approved these changes

2020-08-16 20:19 UTC, merged